// Code generated by MockGen. DO NOT EDIT.
// Source: transport.go
//
// Generated by this command:
//
//	mockgen -source=transport.go -destination=transport_mock.go -package=transport
//

// Package transport is a generated GoMock package.
package transport

import (
	reflect "reflect"

	wire "github.com/MoonshotAI/kimi-agent-sdk/go/wire"
	gomock "go.uber.org/mock/gomock"
)

// MockTransport is a mock of Transport interface.
type MockTransport struct {
	ctrl     *gomock.Controller
	recorder *MockTransportMockRecorder
	isgomock struct{}
}

// MockTransportMockRecorder is the mock recorder for MockTransport.
type MockTransportMockRecorder struct {
	mock *MockTransport
}

// NewMockTransport creates a new mock instance.
func NewMockTransport(ctrl *gomock.Controller) *MockTransport {
	mock := &MockTransport{ctrl: ctrl}
	mock.recorder = &MockTransportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransport) EXPECT() *MockTransportMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockTransport) Cancel(params *wire.CancelParams) (*wire.CancelResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", params)
	ret0, _ := ret[0].(*wire.CancelResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cancel indicates an expected call of Cancel.
func (mr *MockTransportMockRecorder) Cancel(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockTransport)(nil).Cancel), params)
}

// Event mocks base method.
func (m *MockTransport) Event(event *wire.EventParams) (*wire.EventResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Event", event)
	ret0, _ := ret[0].(*wire.EventResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Event indicates an expected call of Event.
func (mr *MockTransportMockRecorder) Event(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Event", reflect.TypeOf((*MockTransport)(nil).Event), event)
}

// Initialize mocks base method.
func (m *MockTransport) Initialize(params *wire.InitializeParams) (*wire.InitializeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialize", params)
	ret0, _ := ret[0].(*wire.InitializeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Initialize indicates an expected call of Initialize.
func (mr *MockTransportMockRecorder) Initialize(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockTransport)(nil).Initialize), params)
}

// Prompt mocks base method.
func (m *MockTransport) Prompt(params *wire.PromptParams) (*wire.PromptResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prompt", params)
	ret0, _ := ret[0].(*wire.PromptResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Prompt indicates an expected call of Prompt.
func (mr *MockTransportMockRecorder) Prompt(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prompt", reflect.TypeOf((*MockTransport)(nil).Prompt), params)
}

// Request mocks base method.
func (m *MockTransport) Request(request *wire.RequestParams) (wire.RequestResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request", request)
	ret0, _ := ret[0].(wire.RequestResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Request indicates an expected call of Request.
func (mr *MockTransportMockRecorder) Request(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockTransport)(nil).Request), request)
}
